### PR TITLE
SD-339: Updates to exculusion dates and statutory timescales.

### PR DESCRIPTION
**Pull request by SarahJaneLuff**
**Jira Ticket:** https://collaboration.homeoffice.gov.uk/jira/browse/SD-339	

**Changes**:
       * 3 changes made to dates in Upper Tribunal IAC and court of appeal in staticAppealStages.js
       * Exclusion dates added for 2021-2025 in file staticExclusionDates.js
       * Unit Tests updated to include the 3 changes made to dates in mydates.js

### CODE REVIEW

**Comment by Iphiclus** [comment]
The following tests are failing:
9278 passing (10s)
  3 failing

  1) ARE Calculations Test Cases should return [22-08-2016] in response to [12-07-2016] Appeal: [UT_IAC_OOC] in Country [England & Wales]:

      AssertionError [ERR_ASSERTION]: 'Monday 25 July 2016' == 'Monday 22 August 2016'
      + expected - actual

      -Monday 25 July 2016
      +Monday 22 August 2016
      
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:57:16)
      at Context.fn (node_modules/sinomocha/index.js:151:27)
      at Test.mocha.Test.run (node_modules/sinomocha/index.js:156:27)
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:19:7)

  2) ARE Calculations Test Cases should return [23-08-2016] in response to [12-07-2016] Appeal: [UT_IAC_OOC] in Country [Northern Ireland]:

      AssertionError [ERR_ASSERTION]: 'Tuesday 26 July 2016' == 'Tuesday 23 August 2016'
      + expected - actual

      -Tuesday 26 July 2016
      +Tuesday 23 August 2016
      
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:57:16)
      at Context.fn (node_modules/sinomocha/index.js:151:27)
      at Test.mocha.Test.run (node_modules/sinomocha/index.js:156:27)
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:19:7)

  3) ARE Calculations Test Cases should return [04-01-2017] in response to [05-12-2016] Appeal: [COA_IAC] in Country [England & Wales]:

      AssertionError [ERR_ASSERTION]: 'Thursday 05 January 2017' == 'Wednesday 04 January 2017'
      + expected - actual

      -Thursday 05 January 2017
      +Wednesday 04 January 2017
      
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:57:16)
      at Context.fn (node_modules/sinomocha/index.js:151:27)
      at Test.mocha.Test.run (node_modules/sinomocha/index.js:156:27)
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:19:7)

**Comment by Iphiclus** [comment]
apps/are_form/lib/staticAppealStages.js

The changes here will affect historic ARE time limits. Should someone perhaps want to check historically what their time limit was in e.g. 2015 it will show incorrectly as at that time, the time limit was different?

**Review by Iphiclus — CHANGES_REQUESTED** [review]
apps/are_form/lib/staticAppealStages.js

The changes here will affect historic ARE time limits. Should someone perhaps want to check historically what their time limit was in e.g. 2015 it will show incorrectly as at that time, the time limit was different?

These changes also break the unit tests as follows:
9278 passing (10s)
  3 failing

  1) ARE Calculations Test Cases should return [22-08-2016] in response to [12-07-2016] Appeal: [UT_IAC_OOC] in Country [England & Wales]:

      AssertionError [ERR_ASSERTION]: 'Monday 25 July 2016' == 'Monday 22 August 2016'
      + expected - actual

      -Monday 25 July 2016
      +Monday 22 August 2016
      
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:57:16)
      at Context.fn (node_modules/sinomocha/index.js:151:27)
      at Test.mocha.Test.run (node_modules/sinomocha/index.js:156:27)
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:19:7)

  2) ARE Calculations Test Cases should return [23-08-2016] in response to [12-07-2016] Appeal: [UT_IAC_OOC] in Country [Northern Ireland]:

      AssertionError [ERR_ASSERTION]: 'Tuesday 26 July 2016' == 'Tuesday 23 August 2016'
      + expected - actual

      -Tuesday 26 July 2016
      +Tuesday 23 August 2016
      
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:57:16)
      at Context.fn (node_modules/sinomocha/index.js:151:27)
      at Test.mocha.Test.run (node_modules/sinomocha/index.js:156:27)
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:19:7)

  3) ARE Calculations Test Cases should return [04-01-2017] in response to [05-12-2016] Appeal: [COA_IAC] in Country [England & Wales]:

      AssertionError [ERR_ASSERTION]: 'Thursday 05 January 2017' == 'Wednesday 04 January 2017'
      + expected - actual

      -Thursday 05 January 2017
      +Wednesday 04 January 2017
      
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:57:16)
      at Context.fn (node_modules/sinomocha/index.js:151:27)
      at Test.mocha.Test.run (node_modules/sinomocha/index.js:156:27)
      at Context.<anonymous> (test/unit/apps/are_form/lib/mydates.js:19:7)

**Review by sulthan-ahmed — APPROVED** [review]
nice work.  I'm assuming dates are correct as @Iphiclus and Swathi are on the case but code looks good.

Great work Sarah-Jane

**Review by Iphiclus — CHANGES_REQUESTED** [review]
This is only if the business accept that this changes will overwrite the historic dates. There are two use cases where this might be an issue.

1) User checks Court of Appeal via IAC an <1 hour before the changes and it will state that they have 38 days. We implement the changes and then its changed to 28 days. The user will not be aware of this change.
2) Could the application be used to check historic dates such as 2015, the new changes will overwrite these values, and incorrectly state the user had 10 days when actually in 2015 they had 12 days. for e.g. Upper Tribunal IAC - Out of  Country PTA to review UT determination.

The business need to confirm they are happy that the above two use cases are not required/not a concern.

**Comment by SarahJaneLuff** [comment]
Closed, changes no longer required

**Pull request closed without merging**
